#datasource properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: Pavan268
    driver-class-name: com.mysql.jdbc.Driver


# create tables dynamically
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

